# Site settings
title: Jonathan Hillis
header-img: img/city.jpg
email: jonathan@discoverboard.com
description: "Jonathan Hillis"
baseurl: ""
url: "http://jonathanhill.is"
twitter_username: jonathanhillis
github_username:  hillisjd
facebook_username:  hillisjd

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8080
